repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
        language_version: python

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        language_version: python
        exclude: tests/.*
        additional_dependencies:
        - types-cachetools
